### PR TITLE
Be able to customize prettifiers by config

### PR DESCRIPTION
**Pull request by Fishdrowned**
## Proposed Changes

- Added `Env::instance()` to provide the ability to get `$env` everywhere
- Added `AppConfig::getConfigData()`
- Modified `FetchKeyInformationQueryHandler::__construct()` to load `$prettifiers` from app config
- Added sample `prettifiers` config

## Further comments
Be able to customize prettifiers by config

### CODE REVIEW

**Comment by hollodotme** [comment]
Hi @Fishdrowned, 

thanks for the PR! 

Before I further look/comment on it, can you please elaborate why you want to make the prettifiers configurable? Do you want to register own prettifiers or does one of the prettifiers not fit your needs?

Thank you.

**Comment by Fishdrowned** [comment]
Hi @hollodotme ,
Because I gzipped some large strings before save them to redis to reduce transfer/memory cost. Then I need to decompress them when browsing.

This use case is uncommon, so I want the extensibility, then I can add my special prettifier to display the decompressed strings.

If you have any plan to provide similar functionality I would be very glad to see it

**Comment by hollodotme** [comment]
@Fishdrowned Ah, I see. Are you able to provide this gzip prettifier class here or as a gist. I don't think that it is an uncommon use case and I already was thinking about such a prettifier in the past.

At the moment all prettifiers are enabled and self-responsible if they can prettify or not.
Changing it to your proposed configuration means that everyone need to opt-in to the prettifiers which would be a BC break.

So my suggestion would be to add the gzip prettifier to the app (like the others) and I will further wrap my head around a solution for registering custom prettifiers. I added #17 for that topic.

What do you think?

**Comment by Fishdrowned** [comment]
My gzip prettifier is useful for me only:
```php
class GzipPrettifier implements PrettifiesString
{
	public function canPrettify(string $data): bool
	{
		// 'g' stands for gzip, 'b' stands for binary
		return isset($data{1}) && $data{0} == 'g' && $data{1} == 'b';
	}

	public function prettify(string $data): string
	{
		return gzinflate(substr($data, 2));
	}
}
```
For me all data are serialized, so no exceptions ('gb' prefix always means gzip).

But this is not safe for everyone, so I don't think it's good to embed this into your repo.

**Comment by Fishdrowned** [comment]
This is what I do currently to load custom prettifiers:
`config/app.php`:
```php
<?php declare(strict_types=1);

use hollodotme\Readis\Application\ReadModel\Prettifiers\HyperLogLogPrettifier;
use hollodotme\Readis\Application\ReadModel\Prettifiers\JsonPrettifier;

include dirname(__DIR__) . '/build/logs/includes.php';

return [
	'baseUrl'     => '',
	'prettifiers' => [
		GzipPrettifier::class,
		JsonPrettifier::class,
		HyperLogLogPrettifier::class,
	],
];
```
I used path `build/logs` because it was in the `.gitignore` entries, to minimize changes, just to made it work.

**Comment by hollodotme** [comment]
Got it, thanks for elaboration. I'd close this PR and would start working on #17.

Btw. you should check for availability of zlib functions in `canPrettify()` as they are not enabled by default on non-windows systems.

**Comment by Fishdrowned** [comment]
> you should check for availability of zlib functions

Thank you for pointing this out!

**Pull request closed without merging**
